import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "./components/header";
import { Analytics } from "@vercel/analytics/react"
import { Inter } from 'next/font/google'
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ 
  subsets: ['latin'], 
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased dark:bg-[#101318] text-[#101318] dark:text-[#dfeff9] scroll-smooth`}
      >
          <Header />
        {children}<Analytics/>
          <Footer />
      </body>
    </html>
  );
}
