import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "./components/header";
import { Analytics } from "@vercel/analytics/react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
          <Header />
        {children}<Analytics/>
      </body>
    </html>
  );
}
